### ISSUE TITLE
NSCoding encodeWithCoder: not being called inside setObject:forKey:

### ISSUE THREAD

**Issue by objectiveSee** [nicklockwood/FXKeychain#10]
Hi! I am using a custom class which conforms to NSCoding.  I am getting an error + assertion inside setObject:forKey:

 NSAssert(!object || (object && data), @"FXKeychain failed to encode object for key '%@', error: %@", key, error);

And [NSPropertyListSerialization propertyListWithData:options:format:error] produces this error:

Property list invalid for format: 200 (property lists cannot contain objects of type 'CFType')

My class conforms to NSCoding so I put a breakpoint on encodeWithCoder: and noticed that encodeWithCoder: is never being called. Any ideas what I am doing wrong? 

Thanks!

**Comment by SolomonBier** [comment]
@nicklockwood can you elaborate on this? How are Foundation objects safer than NSCoding complaint objects?

**Comment by nicklockwood** [comment]
@SolomonBier Almost any object could be NSCoding compliant, including most of foundation and UIKit, and custom objects in your app.

If a malicious party has the ability to create a file which, when opened by your app, can create any kind of object, or tree of objects, they might very well be able to find a code injection vulnerability. For example they might instantiate a UIWebView (which is NSCoding compliant) and somehow get it to open a URL.

The basic foundation objects supported by Plists don't run any interesting code in their constructors, so it's pretty much impossible to do anything dangerous by instantiating them in any combination.
