### ISSUE TITLE
Expected a type / Unknown property attribute 'nullable' errors

### ISSUE THREAD

**Issue by kraftydevil** [nicklockwood/FXKeychain#30]
Cocoapods recently updated to 1.5.3 and I started getting the attached errors:
![screen shot 2015-05-25 at 2 01 52 am](https://cloud.githubusercontent.com/assets/1315619/7793414/873786e0-028c-11e5-83b1-cd4866a58a81.png)

I'm unfamiliar with nullable or nonnull. What is going on?

Also, 1.5.2 worked well but I can't get back to it even when explicitly asking for:
pod 'FXKeychain', '~> 1.5.2'.

**Comment by nicklockwood** [comment]
Are you using Xcode 6.3? nullable/nonnull were introduced in that version.

**Comment by kraftydevil** [comment]
I'm using Xcode 6.2 on Mavericks OS X 10.9.5 and don't want to risk any updates messing up my environment.

Apparently the latest Xcode can be installed on Mavericks but not run. This is according to a comment here: http://appleinsider.com/articles/15/04/08/apple-releases-xcode-63-with-force-touch-support-swift-12-with-improved-compilers

On my machine, I see it as an incompatible update:
![screen shot 2015-05-25 at 10 50 59 am](https://cloud.githubusercontent.com/assets/1315619/7798776/5aa1b12e-02cc-11e5-9c90-bda991765e67.png)

Is there any way I can use 1.5.2? I'm approaching a release and I've had problems with OS / Xcode upgrades in the past.

**Comment by nicklockwood** [comment]
There's no reason why you shouldn't be able to just download 1.5.2 from CocoaPods as it's still on Github. Perhaps you need to delete your pods or something? Maybe ask CocoaPods support.

Failing that, you can just install FXKeychain in your project manually by downloading it from GitHub and following the instructions in the README file.

**Comment by kraftydevil** [comment]
Yeah I'll follow up with cocoapods.

It's very odd that even when specifying 1.5.2 I get 1.5.3. I have removed
the pod completely and tried to re-install but still I get 1.5.3!

Thanks much.

**Comment by kraftydevil** [comment]
FYI the issue I was having was that I was using '~>' to refer to the version.

That means that when listing like so:
pod 'FXKeychain', '~> 1.5.2'

It means cocoapods will look for 1.5.2 or the most recent update since 1.5.2 if it exists. Hence 1.5.3 kept installing.

I changed it to be more explicit:
pod 'FXKeychain', '1.5.2'

Either way, the important point is that you need Xcode 6.3 for FXKeychain 1.5.3 to build.
